### ISSUE TITLE
Bug in 'aws_iam_access_keys' resource

### ISSUE THREAD

**Issue by Rohit1509** [inspec/inspec-aws#901]
Lazy loading not working for 'aws_iam_access_keys' resource

# Describe the problem
For resource pack version v1.83.0 just before lazy loading was added this resource was working fine.
<img width="518" alt="bug1" src="https://user-images.githubusercontent.com/42916862/166001284-78e20425-1cdd-45f7-9343-f515dd71c41b.PNG">

For latest resource pack version v1.83.8 we are not getting any API response
<img width="509" alt="Bug2" src="https://user-images.githubusercontent.com/42916862/166001363-0942520c-0b69-4e02-8682-abff4a2a236a.PNG">

**Comment by sathish-progress** [comment]
@Rohit1509 , I just fixed this. Could you please remove the inspec.lock and try again ?

**Comment by Rohit1509** [comment]
@sathish-progress , the issue is still not resolved.

![image](https://user-images.githubusercontent.com/42916862/166835398-291a95f1-06e3-4a38-99e0-ef1c898608ee.png)

![image](https://user-images.githubusercontent.com/42916862/166835525-237d6031-eef5-4fa7-a575-763dbf082d48.png)

**Comment by Rohit1509** [comment]
Pretty much every function is giving out errors

**Comment by sathish-progress** [comment]
@Rohit1509 , thanks for pointing out the issues, the above PR fixes the issues.

**Comment by Rohit1509** [comment]
Hi @sathish-progress , there was still a bug in the code. Here is the PR: https://github.com/inspec/inspec-aws/pull/904 for that bugfix.

**Comment by Vasu1105** [comment]
Closing this Fixed in #904
